name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy Documenter.jl docs
        uses: TuringLang/actions/DocsDocumenter@main
        with:
          add-navbar: false
        # Plots.jl works fine without this setting, but it does print an extra
        # message 'GKS: cannot open display - headless operation mode active'
        # so this just suppresses that message.
        env:
          GKSwstype: 100
