name: Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  runic:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # 3.0.2
      - uses: julia-actions/cache@a45e8fa8be21c18a06b7177052533149e61e9b38 # 3.1.0

      - name: Install JuliaFormatter
        run: |
          julia -e 'using Pkg; Pkg.Apps.add(name="JuliaFormatter", version=v"2.10.1")'

      - name: Check formatting
        run: |
          ${HOME}/.julia/bin/jlfmt --check --verbose .
