name: CI (Pigeons ext)

on:
  push:
    branches:
      - main
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

# Cancel existing tests on the same PR if a new commit is added to a pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/main' }}


jobs:
  test-pigeons:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        version:
          - 1
          - 1.11

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1

      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # 3.0.2
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@a45e8fa8be21c18a06b7177052533149e61e9b38 # 3.1.0

      - run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate()'
          julia --project=. main.jl
        working-directory: test/pigeons
